/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       AR_CC_RETRY_CUSTOMER_GROUPS TABLE SCRIPT
       $Version 1.0
   REM ============================================================================
   REM
   REM NAME...: AR_CC_RETRY_CUSTOMER_GROUPS

   REM
   REM DESC...: Customer Group Table for ASP-5561 AR_IB_CreditCardRetry
   REM
   REM
   REM FILES..: none
   REM
   REM HISTORY:
   REM
   REM WHO                  WHAT                                                 WHEN
   REM --------------       ----------------------------------------------      ----------
   REM Gowthami Pola     	Customer Group Table                          		08/07/2021
   REM
   REM ===============================================================================
   REM
   REM ===================================================================================

   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
DROP TABLE FUSIONINTEGRATION.AR_CC_RETRY_CUSTOMER_GROUPS;
/

CREATE TABLE FUSIONINTEGRATION.AR_CC_RETRY_CUSTOMER_GROUPS (
CUSTOMER_GROUP_ID   		  												NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY INCREMENT BY 1 START WITH 1         
,CUSTOMER_GROUP_NAME          												VARCHAR2(1000) 
,ACTIVE_FLAG                  												VARCHAR2(10)   
,PRIORITY                  													NUMBER         
,LAST_UPDATE_DATE             												DATE           
,LAST_UPDATED_BY              												VARCHAR2(64)   
,CREATED_BY                   												VARCHAR2(64)   
,CREATION_DATE                												DATE 
,CONSTRAINT AR_CC_RETRY_CUSTOMER_GROUPS_CUSTOMER_GROUP_ID_PK				PRIMARY KEY(CUSTOMER_GROUP_ID)
,CONSTRAINT AR_CC_RETRY_CUSTOMER_GROUP_NAME_UNQ 	UNIQUE (CUSTOMER_GROUP_NAME)
);
/

SHOW ERRORS
/