/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       AR_CC_RETRY_ERROR_CODE_MAPPING TABLE SCRIPT
       $Version 1.0
   REM ============================================================================
   REM
   REM NAME...: AR_CC_RETRY_ERROR_CODE_MAPPING

   REM
   REM DESC...: Error Mapping Table for ASP-5561 AR_IB_CreditCardRetry
   REM
   REM
   REM FILES..: none
   REM
   REM HISTORY:
   REM
   REM WHO                  WHAT                                                 WHEN
   REM --------------       ----------------------------------------------      ----------
   REM Gowthami Pola     	Error Mapping Table                  				08/07/2021
   REM
   REM ===============================================================================
   REM
   REM ===================================================================================

   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
DROP TABLE FUSIONINTEGRATION.AR_CC_RETRY_ERROR_CODE_MAPPING;
/

CREATE TABLE FUSIONINTEGRATION.AR_CC_RETRY_ERROR_CODE_MAPPING (
RECORD_ID 															     	NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY INCREMENT BY 1 START WITH 1
,ERROR_CODE_ID     															NUMBER       
,ERROR_LABEL_ID   		 													NUMBER       
,ERROR_CODE                													VARCHAR2(60) 
,ERROR_LABEL               													VARCHAR2(60) 
,USER_ERROR_LABEL           												VARCHAR2(60)
,LAST_UPDATE_DATE          													DATE         
,LAST_UPDATED_BY           													VARCHAR2(64) 
,CREATED_BY                													VARCHAR2(64) 
,CREATION_DATE             													DATE 
,CONSTRAINT AR_CC_RETRY_ERROR_CODE_MAPPING_RECORD_ID_PK 	PRIMARY KEY (RECORD_ID)
,CONSTRAINT AR_CC_RETRY_ERROR_CODE_MAPPING_ERROR_CODE_ID_FK 	FOREIGN KEY (ERROR_CODE_ID) REFERENCES AR_CC_RETRY_ERROR_CODES(ERROR_CODE_ID)
  ON DELETE CASCADE
,CONSTRAINT AR_CC_RETRY_ERROR_CODE_MAPPING_ERROR_LABEL_ID_FK 	FOREIGN KEY (ERROR_LABEL_ID) REFERENCES AR_CC_RETRY_ERROR_LABELS(ERROR_LABEL_ID)   
ON DELETE CASCADE
,CONSTRAINT AR_CC_RETRY_ERROR_CODE_MAPPING_ERROR_CODEID_ERROR_LABEL_ID_UNQ 	UNIQUE (ERROR_CODE_ID,ERROR_CODE,ERROR_LABEL_ID)
);
/
CREATE INDEX AR_CC_RETRY_ERROR_CODE_MAPPING_ERROR_CODE_IDX ON FUSIONINTEGRATION.AR_CC_RETRY_ERROR_CODE_MAPPING (ERROR_CODE) ;
/

SHOW ERRORS
/