/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       AR_CC_RETRY_CG_RETRY_RULES TABLE SCRIPT
       $Version 1.0
   REM ============================================================================
   REM
   REM NAME...: AR_CC_RETRY_CG_RETRY_RULES

   REM
   REM DESC...: Retry Rules Table for ASP-5561 AR_IB_CreditCardRetry
   REM
   REM
   REM FILES..: none
   REM
   REM HISTORY:
   REM
   REM WHO                  WHAT                                                 WHEN
   REM --------------       ----------------------------------------------      ----------
   REM Gowthami Pola     	Retry Rules Table                  					08/07/2021
   REM
   REM ===============================================================================
   REM
   REM ===================================================================================

   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
DROP TABLE FUSIONINTEGRATION.AR_CC_RETRY_CG_RETRY_RULES;
/

CREATE TABLE FUSIONINTEGRATION.AR_CC_RETRY_CG_RETRY_RULES (
RECORD_ID 																							NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY INCREMENT BY 1 START WITH 1
,CUSTOMER_GROUP_ID         		  																	NUMBER        
,CUSTOMER_GROUP_NAME          																		VARCHAR2(1000) 
,ERROR_LABEL_ID       		  																		NUMBER         
,ERROR_LABEL                  																		VARCHAR2(60)   
,USER_ERROR_LABEL																					VARCHAR2(60)
,LAST_UPDATE_DATE             																		DATE           
,LAST_UPDATED_BY              																		VARCHAR2(64)   
,CREATED_BY                   																		VARCHAR2(64)   
,CREATION_DATE                																		DATE           
,ACTION																								VARCHAR2(100)
,RETRY_TIME																							VARCHAR2(100)
,INTERVAL_TYPE                																		VARCHAR2(100)  
,RETRY_INTERVAL               																		NUMBER         
,DAY																								NUMBER
,HOUR																								NUMBER
,ATTEMPT_ID          		  																		NUMBER         
,ATTEMPT_NAME                 																		VARCHAR2(50)
,CONSTRAINT AR_CC_RETRY_CG_RETRY_RULES_RECORD_ID_PK 					PRIMARY KEY (RECORD_ID)
,CONSTRAINT AR_CC_RETRY_CG_RETRY_RULES_CUSTOMER_GROUP_ID_FK 	FOREIGN KEY (CUSTOMER_GROUP_ID) REFERENCES AR_CC_RETRY_CUSTOMER_GROUPS(CUSTOMER_GROUP_ID)
  ON DELETE CASCADE
,CONSTRAINT AR_CC_RETRY_CG_RETRY_RULES_ERROR_LABEL_ID_FK 	FOREIGN KEY (ERROR_LABEL_ID) REFERENCES AR_CC_RETRY_ERROR_LABELS(ERROR_LABEL_ID)
  ON DELETE CASCADE
,CONSTRAINT AR_CC_RETRY_CG_RETRY_RULES_CG_RETRY_ID_ERROR_LABEL_ID_ATTEMPT_ID_UNQ UNIQUE (CUSTOMER_GROUP_ID,ERROR_LABEL_ID,ATTEMPT_ID)
);
/
SHOW ERRORS
/