/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       AR_CC_RETRY_ERROR_LABELS TABLE SCRIPT
       $Version 1.0
   REM ============================================================================
   REM
   REM NAME...: AR_CC_RETRY_ERROR_LABELS

   REM
   REM DESC...: Error Label Table for ASP-5561 AR_IB_CreditCardRetry
   REM
   REM
   REM FILES..: none
   REM
   REM HISTORY:
   REM
   REM WHO                  WHAT                                                 WHEN
   REM --------------       ----------------------------------------------      ----------
   REM Gowthami Pola     	Error Label Table                  					08/07/2021
   REM
   REM ===============================================================================
   REM
   REM ===================================================================================

   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
DROP TABLE FUSIONINTEGRATION.AR_CC_RETRY_ERROR_LABELS;
/

CREATE TABLE FUSIONINTEGRATION.AR_CC_RETRY_ERROR_LABELS (
ERROR_LABEL_ID   			 								NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY INCREMENT BY 1 START WITH 1       
,ERROR_LABEL               									VARCHAR2(60) 
,USER_ERROR_LABEL											VARCHAR2(60)
,LAST_UPDATE_DATE          									DATE         
,LAST_UPDATED_BY           									VARCHAR2(64) 
,CREATED_BY                									VARCHAR2(64) 
,CREATION_DATE             									DATE 
,CONSTRAINT AR_CC_RETRY_ERROR_LABELS_ERROR_LABEL_ID_PK 		PRIMARY KEY(ERROR_LABEL_ID)
,CONSTRAINT AR_CC_RETRY_ERROR_LABELS_ERROR_LABEL_UNQ	    UNIQUE(ERROR_LABEL)
,CONSTRAINT AR_CC_RETRY_ERROR_LABELS_USER_ERROR_LABEL_UNQ 	UNIQUE(USER_ERROR_LABEL)
);
/
SHOW ERRORS
/