/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       AR_CC_RETRY_CG_CONFIG_RULES TABLE SCRIPT
       $Version 1.0
   REM ============================================================================
   REM
   REM NAME...: AR_CC_RETRY_CG_CONFIG_RULES

   REM
   REM DESC...: Customer Group Configuration Table for ASP-5561 AR_IB_CreditCardRetry
   REM
   REM
   REM FILES..: none
   REM
   REM HISTORY:
   REM
   REM WHO                  WHAT                                                 WHEN
   REM --------------       ----------------------------------------------      ----------
   REM Gowthami Pola     	Customer Group Configuration Table                  08/07/2021
   REM
   REM ===============================================================================
   REM
   REM ===================================================================================

   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
DROP TABLE FUSIONINTEGRATION.AR_CC_RETRY_CG_CONFIG_RULES;
/

CREATE TABLE FUSIONINTEGRATION.AR_CC_RETRY_CG_CONFIG_RULES (
RECORD_ID 															NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY INCREMENT BY 1 START WITH 1
,CUSTOMER_GROUP_ID         		  									NUMBER         
,CUSTOMER_GROUP_NAME          										VARCHAR2(1000) 
,ATTRIBUTE_ID         		  										NUMBER         
,ATTRIBUTE_NAME               										VARCHAR2(500)  
,ATTRIBUTE_VALUE              										VARCHAR2(500)  
,LAST_UPDATE_DATE             										DATE           
,LAST_UPDATED_BY              										VARCHAR2(64)   
,CREATED_BY                   										VARCHAR2(64)   
,CREATION_DATE                										DATE
,CONSTRAINT AR_CC_RETRY_CG_CONFIG_RULES_RECORD_ID_PK PRIMARY KEY (RECORD_ID)
,CONSTRAINT AR_CC_RETRY_CG_CONFIG_RULES_CUSTOMER_GROUP_ID_FK FOREIGN KEY (CUSTOMER_GROUP_ID) REFERENCES AR_CC_RETRY_CUSTOMER_GROUPS(CUSTOMER_GROUP_ID)
  ON DELETE CASCADE
,CONSTRAINT AR_CC_RETRY_CG_CONFIG_RULES_ATTRIBUTE_ID_FK FOREIGN KEY (ATTRIBUTE_ID) REFERENCES AR_CC_RETRY_CG_ATTRIBUTES (ATTRIBUTE_ID)
 ON DELETE CASCADE
,CONSTRAINT AR_CC_RETRY_CG_CONFIG_RULES_CUSTOMER_GROUP_ID_ATTRIBUTE_ID_UNQ UNIQUE (CUSTOMER_GROUP_ID,ATTRIBUTE_ID,ATTRIBUTE_NAME)
);
/

CREATE INDEX AR_CC_RETRY_CG_CONFIG_RULES_NAMEVALUE_IDX ON FUSIONINTEGRATION.AR_CC_RETRY_CG_CONFIG_RULES (ATTRIBUTE_NAME,ATTRIBUTE_VALUE) ;
/

SHOW ERRORS
/