
create or replace PACKAGE GL_ADP_COA_MAP_PKG AS

PROCEDURE JL_INSERT_SRC_SEG (P_RECORD IN GL_ADP_SRC_REC_TYPE);
PROCEDURE JL_CONC_SEG_TRANS(P_IN_CODE_IDENTIFIER IN NUMBER);
PROCEDURE JL_CONC_DATA_DEL(P_IN_CODE_IDENTIFIER IN NUMBER);
PROCEDURE JL_CONC_COMMIT(P_IN_CODE_IDENTIFIER IN NUMBER);
END GL_ADP_COA_MAP_PKG;

/