
  CREATE TABLE "FUSIONINTEGRATION"."DS_OSS_SFDC_APTTUS_ORD_T" 
   (	"APTTUS_ORDER_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ERROR_DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"STAGE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_NUM" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_ON" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_BY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATED_ON" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "PK_APTTUS_ORDER_ID" PRIMARY KEY ("APTTUS_ORDER_ID", "OIC_INSTANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  GRANT SELECT ON "FUSIONINTEGRATION"."DS_OSS_SFDC_APTTUS_ORD_T" TO "FUSION_RO";
