
create or replace PACKAGE AP_XACTLY_MAP_PKG AS

PROCEDURE AP_INSERT_SRC_SEG(P_RECORD IN AP_XACTLY_SRC_REC_TYPE);
PROCEDURE XACTLY_DATA_DEL(P_IN_CODE_IDENTIFIER IN NUMBER);
PROCEDURE AP_CONC_COMMIT(P_IN_CODE_IDENTIFIER IN NUMBER);
END AP_XACTLY_MAP_PKG;

/