  CREATE TABLE "FUSIONINTEGRATION"."CIF_PROCESS_INSTANCE_TBL" 
   (	"INSTANCE_ID" NUMBER NOT NULL ENABLE, 
	"INTEGRATION_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INTEGRATION_PATTERN" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_DATE" DATE NOT NULL ENABLE, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"STATUS_TIME" DATE, 
	"ATTRIBUTE1" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE11" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE12" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE13" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE14" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE15" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AIC_INSTANCE_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE UNIQUE INDEX "FUSIONINTEGRATION"."CIF_PROCESS_INSTANCE_TBL_N1" ON "FUSIONINTEGRATION"."CIF_PROCESS_INSTANCE_TBL" ("INSTANCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;