/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
       DS_COST_CENTER TABLE SCRIPT
       $Version 1.0
   REM ========================================================================================================
   REM
   REM NAME...: DS_COST_CENTER

   REM
   REM DESC... : Crosswalk table for Cost center
   REM
   REM
   REM FILES..: Cost_center.csv
   REM
   REM HISTORY:
   REM
   REM WHO                      WHAT                                              WHEN
   REM --------------       ----------------------------------------------     ----------
   REM Divyanshu Anand      Stage Table to store crosswalk information		   20/05/2021
   REM
   REM ==============================================================================================
   REM
   REM ==============================================================================================

   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
DROP TABLE "FUSIONINTEGRATION"."DS_COST_CENTER";
/ 

CREATE TABLE "FUSIONINTEGRATION"."DS_COST_CENTER" 
   (            
    COST_CENTER VARCHAR2(30),
	SOURCESYSTEMID VARCHAR2(30),
	DESCRIPTION VARCHAR2(240)
	);
/
INSERT ALL
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('0000','000','Default')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1111','130','Technical Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1121','140','Product Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1211','100','Professional Services')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1212','101','Real Estate Prof Services')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1213','102','Partner Success')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1214','110','Customer Success')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1221','160','Customer Readiness')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1231','181','Enterprise CSM')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1232','182','Commercial CSM')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1233','183','Digital CSM')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1234','170','Customer Value Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1241','120','Customer Service')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1242','121','Enterprise Support')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1243','122','Technical Support')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1244','123','Subscription Management Support')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1251','152','Customer Success Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1261','150','Operations - Digital Certs')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1262','151','Services Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1226','180','Customer Success Managers')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1911','199','COS Allocation - Subscription')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('1921','198','COS Allocation - ProServ')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2111','200','Corporate Admin')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2121','220','HR Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2122','222','Talent Development')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2123','223','Total Rewards')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2124','224','HR Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2125','225','HRBP')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2126','221','Recruiting')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2131','230','Legal Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2132','231','Security Empl & Litig')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2133','232','IP Prod & Reg Affairs')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2134','233','Global Contract')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2141','245','Security and Workplace Services')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2142','270','Real Estate & Workplace Srv')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2151','210','Finance Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2152','211','Accounting')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2153','212','Revenue Ops')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2154','213','FP&A')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2155','214','Finance Ops')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2156','215','Investor Relations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2157','216','Internal Audit')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2161','201','Corporate Development')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2211','240','Risk Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2221','249','Global Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2231','250','Information Technology')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2241','251','Enterprise Applications')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2251','253','Information Security')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2261','260','Business Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2271','280','Program Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2311','252','Business Intelligence')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2811','999','Allocated Costs')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('2911','299','G&A Allocation')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3111','300','Prod Dev: Platform')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3121','302','Prod Dev: Infra Engineering')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3141','311','Prod Dev: RE & Dig Closing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3151','312','Prod Dev: RON')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3181','380','Prod Dev: Eng Services')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3191','390','Prod Dev MGMT')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3211','301','Global Partner Solutions')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3231','340','Prod Dev: CLM')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3241','350','Prod Dev: Identity')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3251','370','Prod Dev: Incubation')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3911','399','R&D Allocation')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4111','500','Sales Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4212','505','Commercial Major AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4213','508','Commercial MM AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4214','509','Commercial SMB AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4215','507','Commercial Verticals AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4216','537','Commercial FinServ AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4217','541','Commercial HLS AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4218','506','Commercial EMG Verts AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4219','533','SMG Public Sector AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4222','532','Commercial Major AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4223','528','Commercial MM AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4224','529','Commercial SMB AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4225','527','Commercial Verticals AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4226','538','Commercial FinServ AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4227','542','Commercial HLS AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4228','536','Commercial EMG Verts AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4229','539','SMG Public Sector AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4251','553','Commercial MDR Mgmt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4252','552','Commercial SDR Mgmt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4266','562','Commercial SE Support')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4311','510','Enterprise Sales AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4313','502','Enterprise Verticals AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4314','504','Enterprise FinServ AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4315','503','Enterprise Public Sector AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4316','514','Enterprise ECS')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4321','515','Enterprise Sales AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4323','518','Enterprise Verticals AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4324','534','Enterprises FinServ AEs Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4325','519','Enterprise Pub Sec AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4341','513','Enterprise MDR')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4351','543','Enterprise MDR Mgmt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4362','563','Enterprise SE Support')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4411','550','Business Development')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4412','575','Real Estate Sales Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4421','551','Channel Sales')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4511','570','Agreement Cloud Strat & Sol')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4611','530','Sales Operations')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4621','531','GTM Productivity')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4631','535','GTM Enablement')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4651','545','Engagement Manager')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4661','546','Professional Sercices Ops')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4662','547','SI Partners Management')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4911','599','Sales Allocation')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5111','400','Marketing Strategy')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5121','410','Corporate Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5133','445','Search Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5134','420','Field Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5151','435','Partner Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5171','470','Website Development')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5172','475','Web Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5181','480','Creative Brand Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5191','455','Segment Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5911','499','Marketing Allocation')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3131','310','Prod Dev: Agree (Sign)')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3161','320','Prod Dev: Developer Program')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3171','330','Prod Dev: Manage & Optimize')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('3221','304','Prod Dev: Design & Research')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4211','520','Corporate Sales AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4221','525','Corporate Sales AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4231','521','Corporate Renewal Managers')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4232','526','Corporate Sales RM Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4241','522','Corp SDR')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4242','523','Corp MDR')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4261','560','Sales Engineering - Corp')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4312','501','Enterprise Geos AE')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4322','517','Enterprise Geos AE Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4331','511','Enterprise Renewal Managers')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4332','516','Enterprise Sales RM Mgt')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4361','561','Sales Engineering - Ent')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('4641','540','Sales Education')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5131','415','Integrated Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5132','440','Lead Generation')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5141','430','Product Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5143','460','Audience Marketing')
INTO DS_COST_CENTER (COST_CENTER,SOURCESYSTEMID,DESCRIPTION) Values('5161','450','eCommerce')
SELECT * FROM DUAL;
/
SHOW ERRORS
/