
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FUSIONINTEGRATION"."DS_CONCUR_GLINTERFACE_V" ("REPORT_CREATION_DATE", "EMPLOYEE_ID", "EMPLOYEE_LAST_NAME", "EMPLOYEE_FIRST_NAME", "REPORT_ID", "EMPLOYEE_DCURACODE", "REPORT_SUBMIT_DATE", "REPORT_PROC_PAYDATE", "REPORT_NAME", "REPORT_ENTRY_EXPTYPENAME", "REPORT_ENTRY_TRANSDATE", "REPORT_ENTRY_FLAG", "REPORT_ENTRY_DES", "REPORT_ENTRY_VENNAME", "REPORT_ENTRY_VENDES", "REPORT_ENTRY_PAYCODE", "REPORT_ENTRY_PAYNAME", "REPORT_PAYMENT_REIMBTYPE", "BILLED_CCARD_ACCNUM", "BILLED_CCARD_ACCDESC", "JOURNAL_PAYERPAY_CNAME", "JOURNAL_PAYEE_PAYTYPENAME", "JOURNAL_AMT", "JOURNAL_ACCCODE", "JOURNAL_DEBIT_CREDIT", "PAYMENT_DCOMPANYCASHACCCODE", "PAYMENT_DCOMPANYLIAACCCODE", "EST_PAYDATE", "DEPARTMENT", "STATUS", "ERROR_CODE", "ERROR_DESCRIPTION", "OIC_INSTANCE_ID", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "REF1", "REF2", "REF4", "REF5", "REF10") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select 
 to_char(to_date(REPORT_CREATION_DATE,'yyyy-mm-dd'),'yyyy/mm/dd')	REPORT_CREATION_DATE
,EMPLOYEE_ID
,EMPLOYEE_LAST_NAME
,EMPLOYEE_FIRST_NAME
,REPORT_ID
,EMPLOYEE_DCURACODE EMPLOYEE_DCURACODE
,to_char(to_date(REPORT_CREATION_DATE,'yyyy-mm-dd'),'yyyy/mm/dd') REPORT_SUBMIT_DATE
,to_char(to_date(REPORT_CREATION_DATE,'yyyy-mm-dd'),'yyyy/mm/dd') REPORT_PROC_PAYDATE
,REPORT_NAME
,REPORT_ENTRY_EXPTYPENAME
,to_char(to_date(REPORT_CREATION_DATE,'yyyy-mm-dd'),'yyyy/mm/dd') REPORT_ENTRY_TRANSDATE
,REPORT_ENTRY_FLAG
,REPORT_ENTRY_DES
,REPORT_ENTRY_VENNAME
,REPORT_ENTRY_VENDES
,REPORT_ENTRY_PAYCODE
,REPORT_ENTRY_PAYNAME
,REPORT_PAYMENT_REIMBTYPE
,BILLED_CCARD_ACCNUM
,BILLED_CCARD_ACCDESC
,JOURNAL_PAYERPAY_CNAME
,JOURNAL_PAYEE_PAYTYPENAME
,JOURNAL_AMT
,JOURNAL_ACCCODE
,'DR'														JOURNAL_DEBIT_CREDIT
,PAYMENT_DCOMPANYCASHACCCODE
,PAYMENT_DCOMPANYLIAACCCODE
,to_char(to_date(REPORT_CREATION_DATE,'yyyy-mm-dd'),'yyyy/mm/dd') 	EST_PAYDATE
,DEPARTMENT
,STATUS
,ERROR_CODE
,ERROR_DESCRIPTION
,OIC_INSTANCE_ID
,ATTRIBUTE1
,ATTRIBUTE2
,ATTRIBUTE3
,ATTRIBUTE4
,ATTRIBUTE5
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyy') REF1
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss') REF2
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss') REF4
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss') REF5
,REPORT_ID||'|'||EMPLOYEE_ID||'|'||EMPLOYEE_FIRST_NAME||'|'||EMPLOYEE_LAST_NAME||'|'||REPORT_ENTRY_EXPTYPENAME||'|'||ATTRIBUTE2  REF10 
from DS_Concur_PaymentBatch_T
where attribute1 = 'GL' and upper(nvl(status,'NA')) not in ('PROCESSED')
union  
  select 
  to_char((to_date(REPORT_CREATION_DATE,'yyyy-mm-dd')),'yyyy/mm/dd') 		REPORT_CREATION_DATE
,'' EMPLOYEE_ID
,'' EMPLOYEE_LAST_NAME
,'' EMPLOYEE_FIRST_NAME
,'' REPORT_ID
,EMPLOYEE_DCURACODE EMPLOYEE_DCURACODE
,to_char((to_date(REPORT_CREATION_DATE,'yyyy-mm-dd')),'yyyy/mm/dd') 	REPORT_SUBMIT_DATE
,to_char((to_date(REPORT_CREATION_DATE,'yyyy-mm-dd')),'yyyy/mm/dd') 	REPORT_PROC_PAYDATE
,'' REPORT_NAME
,'' REPORT_ENTRY_EXPTYPENAME
,to_char((to_date(REPORT_CREATION_DATE,'yyyy-mm-dd')),'yyyy/mm/dd') 	REPORT_ENTRY_TRANSDATE
,'' REPORT_ENTRY_FLAG
,'' REPORT_ENTRY_DES
,'' REPORT_ENTRY_VENNAME
,'' REPORT_ENTRY_VENDES
,'' REPORT_ENTRY_PAYCODE
,'' REPORT_ENTRY_PAYNAME
,'' REPORT_PAYMENT_REIMBTYPE
,'' BILLED_CCARD_ACCNUM
,'' BILLED_CCARD_ACCDESC
,'' JOURNAL_PAYERPAY_CNAME
,'' JOURNAL_PAYEE_PAYTYPENAME
,to_char(sum(JOURNAL_AMT)) JOURNAL_AMT
,'' JOURNAL_ACCCODE
,'CR'														JOURNAL_DEBIT_CREDIT
,'' PAYMENT_DCOMPANYCASHACCCODE
,'' PAYMENT_DCOMPANYLIAACCCODE
,to_char((to_date(REPORT_CREATION_DATE,'yyyy-mm-dd')),'yyyy/mm/dd') 	EST_PAYDATE
,'' DEPARTMENT
,STATUS STATUS
,'' ERROR_CODE
,'' ERROR_DESCRIPTION
,OIC_INSTANCE_ID OIC_INSTANCE_ID
,'GL' ATTRIBUTE1
,'' ATTRIBUTE2
,ATTRIBUTE3
,'' ATTRIBUTE4
,'' ATTRIBUTE5
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyy') REF1
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss') REF2
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss') REF4
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss') REF5
,ATTRIBUTE3||'  '||to_char(sysdate,'mmddyyyyhh24miss')||' Concur_Paid'  REF10 
from DS_Concur_PaymentBatch_T
where attribute1 = 'GL' and upper(nvl(status,'NA')) not in ('PROCESSED')
group by 
ATTRIBUTE3 , STATUS ,to_char((to_date(REPORT_CREATION_DATE,'yyyy-mm-dd')),'yyyy/mm/dd') , OIC_INSTANCE_ID , EMPLOYEE_DCURACODE;
